### ISSUE TITLE
WWW::Spotify in the 2020. Working?

### ISSUE THREAD

**Issue by x09** [trs-80/WWW-Spotify#7]
Hi,

Tried your module. 

```
use strict;
use warnings;
use utf8;
use WWW::Spotify;
use Data::Dumper;

my $spotify = WWW::Spotify->new();
my $result;
#$result = $spotify->user( 'k7h7fqn1njr4h19ae6u72exbl' ); # my username
$spotify->oauth_client_id('myclient_id_1234567890');
$spotify->oauth_client_secret('my_secret_1234567890');
$result = $spotify->album('0sNOF9WDwhWunNAHPD3Baj'); # from example

print Dumper $result;
```
run, and get

```
$VAR1 = '{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}';
```

What I did wrong?

**Comment by oalders** [comment]
@x09 I've just uploaded a fix which @trs-80 has kindly put together. It should be available in a few minutes if you'd like to test it.

**Comment by trs-80** [comment]
You may need to leverage the new “force_client_auth” method, several calls
now require a token that previously did not. The force_client_auth should
make it more flexible.

This module has not been updated in a while so there are probably endpoints
that are not supported currently, let me know if you are interested in
having those added.

**Comment by x09** [comment]
Work! Thanks!

**Comment by oalders** [comment]
Excellent! I will close this ticket then. 🎉
